name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set short SHA version
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ env.VERSION }} .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ env.VERSION }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          VERSION: ${{ github.sha }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: VERSION
          script: |
            cd ~/DevOps || git clone https://github.com/valeria-frckova/DevOps.git && cd DevOps
            git pull

            # convert full sha → first 7 chars
            VERSION=${VERSION::7}

            echo "Deploying version $VERSION"

            sudo VERSION=$VERSION docker-compose down
            sudo VERSION=$VERSION docker-compose up -d